// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEauitzGRetQ5quY9kcSR8absmALkNsiI',
    appId: '1:801859574811:android:4ea0750a88c9a63929ecbe',
    messagingSenderId: '801859574811',
    projectId: 'gym-controller-8dbe8',
    storageBucket: 'gym-controller-8dbe8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA897U8dzAFjdHixMpYITvLFok6RnwcuFk',
    appId: '1:801859574811:ios:3c2fbecc3389d83429ecbe',
    messagingSenderId: '801859574811',
    projectId: 'gym-controller-8dbe8',
    storageBucket: 'gym-controller-8dbe8.appspot.com',
    androidClientId: '801859574811-dm6a7bckdub4qbm1u0dl4b07nkakq8eo.apps.googleusercontent.com',
    iosClientId: '801859574811-hvlju8uvbpj32dh2egrhpjjn838eqsil.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymApp',
  );
}
